spring.application.name=products-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/products}
spring.datasource.username=${DB_USER:products}
spring.datasource.password=${DB_PASSWORD:products}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
